structure(list(url = "https://api.tiingo.com/tiingo/daily/badticker2/prices", 
    status_code = 404L, headers = structure(list(server = "nginx/1.14.0 (Ubuntu)", 
        date = "Mon, 20 Jul 2020 14:53:20 GMT", `content-type` = "application/json", 
        `content-length` = "49", vary = "Accept, Cookie, Origin", 
        `x-frame-options` = "SAMEORIGIN", allow = "GET, HEAD, OPTIONS"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.14.0 (Ubuntu)", 
            date = "Mon, 20 Jul 2020 14:53:20 GMT", `content-type` = "application/json", 
            `content-length` = "49", vary = "Accept, Cookie, Origin", 
            `x-frame-options` = "SAMEORIGIN", allow = "GET, HEAD, OPTIONS"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"detail\":\"Error: Ticker 'BADTICKER2' not found\"}"), 
    date = structure(1595256800, class = c("POSIXct", "POSIXt"
    ), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.2e-05, 
    connect = 2.3e-05, pretransfer = 6.6e-05, starttransfer = 0.085636, 
    total = 0.085668)), class = "response")
