structure(list(url = "https://api.tiingo.com/iex/badticker/prices?startDate=2019-07-21&endDate=2020-07-20&resampleFreq=5min", 
    status_code = 404L, headers = structure(list(server = "nginx/1.14.0 (Ubuntu)", 
        date = "Mon, 20 Jul 2020 15:04:43 GMT", `content-type` = "application/json", 
        `content-length` = "23", vary = "Accept, Cookie, Origin", 
        `x-frame-options` = "SAMEORIGIN", allow = "GET, HEAD, OPTIONS"), class = c("insensitive", 
    "list")), all_headers = list(list(status = 404L, version = "HTTP/1.1", 
        headers = structure(list(server = "nginx/1.14.0 (Ubuntu)", 
            date = "Mon, 20 Jul 2020 15:04:43 GMT", `content-type` = "application/json", 
            `content-length` = "23", vary = "Accept, Cookie, Origin", 
            `x-frame-options` = "SAMEORIGIN", allow = "GET, HEAD, OPTIONS"), class = c("insensitive", 
        "list")))), cookies = structure(list(domain = logical(0), 
        flag = logical(0), path = logical(0), secure = logical(0), 
        expiration = structure(numeric(0), class = c("POSIXct", 
        "POSIXt")), name = logical(0), value = logical(0)), row.names = integer(0), class = "data.frame"), 
    content = charToRaw("{\"detail\":\"Not found.\"}"), date = structure(1595257483, class = c("POSIXct", 
    "POSIXt"), tzone = "GMT"), times = c(redirect = 0, namelookup = 2.6e-05, 
    connect = 2.8e-05, pretransfer = 7.8e-05, starttransfer = 0.073744, 
    total = 0.073775)), class = "response")
